name: ps-container
networks:
  postgres_network:
    driver: bridge
volumes:
  postgresdata: null
services:
  # Add to docker-compose.yml
  timescaledb:
    image: timescale/timescaledb:latest-pg18
    environment:
      POSTGRES_USER: fleetpulse
      POSTGRES_PASSWORD: fleetpulse_dev
      POSTGRES_DB: fleetpulse
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/
      - ../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - postgres_network
      