name: redpanda-fleetpulse
networks:
  redpanda_network:
    external: true
    name: redpanda_network

services:
  # React+Vite frontend
  fleetpulse-frontend:
    image: fleetpulse-frontend:1.0
    env_file:
      - .env
    ports:
      - "5173:80"
    networks:
      - redpanda_network