name: redpanda-fleetpulse
networks:
  redpanda_network:
    external: true
    name: redpanda_network

services:
  # Add to docker-compose.yml
  db-writer:
    image: fleetpulse-dbwriter:1.0
    env_file:
      - .env
    ports:
      - "8180:8080"
    networks:
      - redpanda_network

  signalr-hub:
    image: fleetpulse-signalrhub:1.0
    env_file:
      - .env
    ports:
      - "8280:8080"
    networks:
      - redpanda_network

  ai-worker:
    image: fleetpulse-ai-worker:1.0
    env_file:
      - .env
    volumes:
      - ../ai-worker/data:/app/data
    ports:
      - "8000:8000"
    networks:
      - redpanda_network