name: redpanda-fleetpulse
networks:
  redpanda_network:
    external: true
    name: redpanda_network

services:
  # SignalRHub mock web app
  fleetpulse-mockfleethub:
    image: fleetpulse-mockfleethub:1.0
    env_file:
      - .env
    ports:
      - "8380:8080"
    networks:
      - redpanda_network